#include<stdint.h>

// GPIO Port 1 Data Register(led connected in 1.0)
#define GPIO_PRT1_DR (*(volatile uint32_t *)0x40040100) //  address for GPIO Port 1 Output Register connected with led
#define GPIO_PRT1_PC (*(volatile uint32_t *)0x40040108) // address for GPIO Port 1 Drive Mode Register
// GPIO Port 3 Pin State Register(switch connected in 3.7)
#define GPIO_PRT3_PS (*(volatile uint32_t *)0x40040304) 
#define GPIO_PRT3_PC (*(volatile uint32_t *)0x40040308)
#define GPIO_PRT3_DR (*(volatile uint32_t *)0x40040300)
// Interrupt configuration and status registers for GPIO Port 3
#define GPIO_PRT3_INTR_CFG (*(volatile uint32_t *)0x4004030C)
#define GPIO_PRT3_INTR (*(volatile uint32_t *)0x40040310)
// NVIC registers for CM0+
#define CM0P_IPR0 (*(volatile uint32_t *)0xE000E400)
#define CM0P_ISER (*(volatile uint32_t *)0xE000E100)
#define CM0P_ICPR (*(volatile uint32_t *)0xE000E280)


int main(){
    enable_irq(); // enable interrupt for GPIO Port 3
    GPIO_PRT1_PC|=(0X6<<0); // Mode 6: Strong pull down ('0'), strong pull up ('1'). Input buffer on.
    GPIO_PRT1_PC|=(0X6<<6);
    GPIO_PRT1_PC|=(0X6<<12);
    GPIO_PRT3_PC|=(2u<<21); // Mode 2: Strong pull down ('0'), weak/resistive pull up (PU). Input buffer on
    GPIO_PRT3_PC|=(2u<<6);
    GPIO_PRT3_DR|=(1<<7); // pull up enabled for switch connected in 3.7
    GPIO_PRT3_DR|=(1<<2);
    GPIO_PRT3_INTR_CFG|=(0x2<<14); // Raising  edge trigger for pin 3.7
    GPIO_PRT3_INTR_CFG|=(0x2<<4); // Raising  edge trigger for pin 3.2
    CM0P_IPR0|=(3<<30); // Priority of interrupt number N+3.
    CM0P_ISER|=(1<<3); // Enable interrupt for GPIO Port 3 (Startup file)
    CM0P_ICPR =0xFFFFFFFF; // Clear all pending interrupt for GPIO Port 3

    while(1){
        GPIO_PRT1_DR|=(1<<2); // turn OFF led
        for( int i=0;i<100000;i++); // delay
        GPIO_PRT1_DR&=~(1<<2); // turn ON led
        for( int i=0;i<100000;i++); // delay
    }
}
void ioss_interrupts_gpio_3_IRQHandler(){
    // Check if interrupt is generated by pin 3.7
    if((GPIO_PRT3_INTR & (1<<7)) !=0){
        GPIO_PRT1_DR ^= (1<<0); // toggle led connected in 1.0
        GPIO_PRT3_INTR |= (1<<7); // clear interrupt for pin 3.7
    }
    // Check if interrupt is generated by pin 3.2
    if((GPIO_PRT3_INTR & (1<<2)) !=0){
        GPIO_PRT1_DR^=(1<<4); // toggle led connected in 1.4
        GPIO_PRT3_INTR |= (1<<2); // clear interrupt for pin 3.2
    }
}